version: "3"
services:
  nginx:
    image: "nginx"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    network_mode: "host"
    volumes:
      - /opt/docker/nginx/certs:/certs
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/sites:/sites
